name: cfpb_analytics
version: 1.0.0
config-version: 2
profile: cfpb_analytics

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets: ["target", "dbt_packages"]

models:
  cfpb_analytics:
    +materialized: view
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: marts
      +materialized: table

vars:
  # used by freshness / incremental watermark docs
  cfpb_min_date: "2015-01-01"
